/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 *
 * Generated by scripts/generate-wcag-level-map.mjs
 * Source: widget-src/data/checklist.json
 */

import type { WCAGLevel, WcagCriterionCode } from "types/wcag";

export interface WcagLevelCriterion {
  code: WcagCriterionCode;
  title: string;
  url: string;
}

export type WcagLevelCriteriaMap = Record<WCAGLevel, readonly WcagLevelCriterion[]>;
export type WcagCriteriaByLevelMap = Record<WCAGLevel, readonly WcagCriterionCode[]>;

export const wcagLevelCriteriaMap: WcagLevelCriteriaMap = {
  "A": [
    {
      "code": "1.1.1",
      "title": "Make sure that all <code>img</code> elements have an <code>alt</code> attribute.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html"
    },
    {
      "code": "1.2.2",
      "title": "Confirm the presence of captions.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/captions-prerecorded.html"
    },
    {
      "code": "1.3.1",
      "title": "Make sure that <code>button</code>, <code>a</code>, and <code>label</code> element content is unique and descriptive.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html"
    },
    {
      "code": "1.3.2",
      "title": "Check to see that keyboard focus order matches the visual layout.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence.html"
    },
    {
      "code": "1.3.3",
      "title": "Double-check that good proximity between content is maintained.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/sensory-characteristics.html"
    },
    {
      "code": "1.4.1",
      "title": "Ensure that links are recognizable as links.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html"
    },
    {
      "code": "1.4.2",
      "title": "Make sure that media does not autoplay.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/audio-control.html"
    },
    {
      "code": "2.1.1",
      "title": "Check to see that all media can be paused.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html"
    },
    {
      "code": "2.1.2",
      "title": "Make sure that SVG utilizing the <code>use</code> element has whitespace between the <code>svg</code> and <code>use</code> elements.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/no-keyboard-trap.html"
    },
    {
      "code": "2.2.1",
      "title": "Allow extending session timeouts.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/timing-adjustable.html"
    },
    {
      "code": "2.2.2",
      "title": "Provide a mechanism to pause background video.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/pause-stop-hide.html"
    },
    {
      "code": "2.3.1",
      "title": "Remove seizure triggers.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/three-flashes-or-below-threshold.html"
    },
    {
      "code": "2.4.1",
      "title": "Provide a skip link and make sure that it is visible when focused.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html"
    },
    {
      "code": "2.4.2",
      "title": "Provide a unique <code>title</code> for each page or view.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html"
    },
    {
      "code": "2.4.3",
      "title": "Ensure a linear content flow.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html"
    },
    {
      "code": "3.1.1",
      "title": "Use a <code>lang</code> attribute on the <code>html</code> element.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html"
    },
    {
      "code": "3.2.2",
      "title": "All inputs in a form are associated with a corresponding <code>label</code> element.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/on-input.html"
    },
    {
      "code": "3.3.1",
      "title": "Make sure that form input errors are displayed in list above the form after submission.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/error-identification.html"
    },
    {
      "code": "4.1.1",
      "title": "Use the <code>th</code> element for table headers (with appropriate <code>scope</code> attributes).",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/parsing.html"
    },
    {
      "code": "4.1.2",
      "title": "Use landmark elements to indicate important content regions.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html"
    }
  ],
  "AA": [
    {
      "code": "1.3.4",
      "title": "Check that the site can be rotated to any orientation.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/orientation.html"
    },
    {
      "code": "1.3.5",
      "title": "Inputs use <code>autocomplete</code> where appropriate.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html"
    },
    {
      "code": "1.4.3",
      "title": "Check the contrast for all normal-sized text.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html"
    },
    {
      "code": "1.4.4",
      "title": "Ensure that viewport zoom is not disabled.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html"
    },
    {
      "code": "1.4.10",
      "title": "Use a simple, straightforward, and consistent layout.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/reflow.html"
    },
    {
      "code": "1.4.11",
      "title": "Check the contrast for all icons.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html"
    },
    {
      "code": "2.4.6",
      "title": "Use heading elements to introduce content.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html"
    },
    {
      "code": "2.4.7",
      "title": "Make sure there is a visible focus style for interactive elements that are navigated to via keyboard input.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html"
    }
  ],
  "AAA": [
    {
      "code": "1.4.8",
      "title": "Use left-aligned text for left-to-right (<abbr>LTR</abbr>) languages, and right-aligned text for right-to-left (<abbr>RTL</abbr>) languages.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/visual-presentation.html"
    },
    {
      "code": "2.3.3",
      "title": "Make sure all animation obeys the <code>prefers-reduced-motion</code> media query.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html"
    },
    {
      "code": "2.5.5",
      "title": "Ensure that button and link icons can be activated with ease.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html"
    },
    {
      "code": "3.1.5",
      "title": "Use plain language and avoid figures of speech, idioms, and complicated metaphors.",
      "url": "https://www.w3.org/WAI/WCAG22/Understanding/reading-level.html"
    }
  ]
} as const;

export const wcagCriteriaByLevel: WcagCriteriaByLevelMap = {
  "A": [
    "1.1.1",
    "1.2.2",
    "1.3.1",
    "1.3.2",
    "1.3.3",
    "1.4.1",
    "1.4.2",
    "2.1.1",
    "2.1.2",
    "2.2.1",
    "2.2.2",
    "2.3.1",
    "2.4.1",
    "2.4.2",
    "2.4.3",
    "3.1.1",
    "3.2.2",
    "3.3.1",
    "4.1.1",
    "4.1.2"
  ],
  "AA": [
    "1.3.4",
    "1.3.5",
    "1.4.3",
    "1.4.4",
    "1.4.10",
    "1.4.11",
    "2.4.6",
    "2.4.7"
  ],
  "AAA": [
    "1.4.8",
    "2.3.3",
    "2.5.5",
    "3.1.5"
  ]
} as const;
